### ISSUE TITLE
Lux and you get

### ISSUE THREAD

**Issue by trimechee** [murrty/youtube-dl-gui#132]
Hello, thank you very much fot this awesome and fantastic amzing downloader 🥇 💯 !

i have suggestion please : it will be even more great if there is integration with ths famous CLI software because yt-dlp may suffer from censorship like youtube-dl on github when youtube- dl was removed from github after a dmca complaint.....

You-Get
Dumb downloader that scrapes the web

You-Getis a tiny command-line utility to download media contents (videos, audios, images) from the Web, in case there is no other handy way to do it.

https://github.com/soimort/you-get

Lux is a fast and simple video downloader built with Go

 Fast and simple video download library and CLI tool written in Go

https://github.com/iawia002/lux

**Comment by murrty** [comment]
I thought about it and I don't think I will be adding these. Youtube-dl (and forks) add a bunch of options that impact downloading, which sadly are omitted from these.

Additionally, the censorship claims are, while valid, not actually a reason to include the other two programs suggested, because they could also be targetted by the RIAA or some other 4 letter company with weird licensing ownership and would cause them to also be removed, but since youtube-dl (and forks may also apply) already has precedent of explicitly being allowed on Github, I don't think they will be going anywhere anytime soon.

Thank you for the suggestion, though.

**Comment by trimechee** [comment]
No worries :) it was just a suggestion, thank you very much for your efforts to make this wonderful downloader :)

**Comment by trimechee** [comment]
Another suggestion, to make Youtube-dl-gui even more powerful, may be it will be great to add support of this cli m3u8 downloader : 

https://github.com/nilaoda/N_m3u8DL-CLI
