### ISSUE TITLE
"Fix v.reddit.com" option now actually breaks Reddit videos

### ISSUE THREAD

**Issue by Hypocee** [murrty/youtube-dl-gui#16]
Edit: Actually it's super simple, the problem occurs with apparently all Reddit videos and I'd overlooked the "fix Reddit videos" checkbox in the settings. When it's turned _on_, Reddit videos cause error spam and come out bad. With it turned _off_, they come out good. Looks like whatever it was fixing isn't true anymore.

When [https://www.reddit.com/r/funny/comments/daefhv/guy_wakes_up_in_the_wrong_house/](https://www.reddit.com/r/funny/comments/daefhv/guy_wakes_up_in_the_wrong_house/) is downloaded with the default options Download type: video, Quality best (or Quality 480p or 360p, the other two I tried), the command line window scrolls through a bunch of yellow errors about "Non-monotonous DTS". The download completes but the video stops or gets out of order at several points.

The video is visibly malformed in some way even when viewing on the Web (big encoding-fail color blocks), but it comes out fine by either:
1. using the same youtube-dl.exe that GUI is using, from the CLI, with no options or 
2. Changing the Download type to Custom with a blank arguments field

Something in your default arguments is apparently breaking something, or at least stopping it from being automatically fixed. Is there a way to capture the generated command line and returned text for further troubleshooting?

**Comment by murrty** [comment]
What version of ffmpeg are you using?

**Comment by murrty** [comment]
since i havent gotten a response in 5 months, i'm gonna consider this defunct

if fix redd.it doesn't work, try updating both youtube-dl and ffmpeg, as it requires ffmpeg. my lines pass to youtube-dl, which has it use ffmpeg instead. if it skips ffmpeg its most likely youtube-dl's fault because i do pass the command to use ffmpeg here: https://github.com/murrty/youtube-dl-gui/blob/ce05a2954ff23043191b04f28aea7f618ea91190/Classes/Download.cs#L123
https://github.com/murrty/youtube-dl-gui/blob/ce05a2954ff23043191b04f28aea7f618ea91190/Classes/Download.cs#L126
https://github.com/murrty/youtube-dl-gui/blob/ce05a2954ff23043191b04f28aea7f618ea91190/Classes/Download.cs#L129
https://github.com/murrty/youtube-dl-gui/blob/ce05a2954ff23043191b04f28aea7f618ea91190/Classes/Download.cs#L132
