### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by HercPoirot** [murrty/youtube-dl-gui#191]
Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression
Erreur	CS1061	'HttpException' ne contient pas de définition pour 'Uri' et aucune méthode d'extension accessible 'Uri' acceptant un premier argument de type 'HttpException' n'a été trouvée (une directive using ou une référence d'assembly est-elle manquante ?)	youtube-dl-gui-updater	xxx\source\repos\youtube-dl-gui\youtube-dl-gui-updater\Logging\Forms\frmException.cs	276	Actif

**Comment by HercPoirot** [comment]
Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression
Erreur		Le fichier de configuration de l'application "App.config" n'est pas valide. Le fichier 'xxxx\source\repos\youtube-dl-gui\youtube-dl-gui\App.config' est introuvable.	youtube-dl-gui	xxxx\source\repos\youtube-dl-gui\youtube-dl-gui\App.config

**Comment by murrty** [comment]
Yes it seems building as is currently isn't possible and I do not blame myself because I do no wrong never ever, I am just simply that good and have never made a single mistake. In fact, it was voluntary so people would LOOK for the fact it's not build-able as a sign of strength that my repo is absolutely fool-proof and can be easily re-built without needing to do some funny things I have done to make it work.

**Comment by HercPoirot** [comment]
I appreciate the irony but I didn’t find any answer.
