### ISSUE TITLE
Improvements - Program improvements

### ISSUE THREAD

**Issue by bovirus** [murrty/youtube-dl-gui#37]
@murrty 

I have some proposal for improvements

**_At first startup detect OS language an set the program in the sanme language_**
At first startup the program check OS language (ex. Italian) and if available set the program with the same language.

Infact there are some warning that I beleieve that could be appear in local language (ex. Italian).

![Youtube-dl-gui-01](https://user-images.githubusercontent.com/1262554/82724807-07bec300-9cd9-11ea-9743-fe7c69e9580a.jpg)
![Youtube-dl-gui-02](https://user-images.githubusercontent.com/1262554/82724809-08575980-9cd9-11ea-9952-7ef82de7f2c2.jpg)
![Youtube-dl-gui-03](https://user-images.githubusercontent.com/1262554/82724810-08575980-9cd9-11ea-9693-46d458f9ea06.jpg)

**_Bigger dafault width for main window_**
At first run the width for main is window is too small.
Please setup a larger widt as default for main window
I know that you can change it but for me should be better to have from first run a bigger width.

![Youtube-dl-gui-04](https://user-images.githubusercontent.com/1262554/82724818-10af9480-9cd9-11ea-92f4-f69957a663d9.jpg)

There are two strings (lblformat and ebst) that should be added to the strings that can be translated.

![Youtube-dl-gui-05](https://user-images.githubusercontent.com/1262554/82724839-2a50dc00-9cd9-11ea-9daa-de2ad0671bf8.jpg)

**_Store setting about audio/video format quality and type_**
The program If I select ex for video MP4 and MP3 should store my settiings and not like now at next startup reset it to "best".

**_Swap postition about file type and quality_**
For me the right order of selection is first file type (ex. MP3 or MP4) and then file quality.
Then vicevesersa like now. My prosal is like this.

![Youtube-dl-gui-06](https://user-images.githubusercontent.com/1262554/82724943-db577680-9cd9-11ea-84f5-c91bbc2223cc.jpg)

**Comment by murrty** [comment]
For the first 3, I can't really realistically do it. The way languages are setup is that they are queried through their file names, and not what's inside to save of read cycles. I don't have an alternative way of identifying language files at the moment, nor can I effectively think of one, so it'll just have to be for the time being.

The main window I decided to keep as-is because it suits the small form-factor I target for my applications, because large programs taking up space is bad for multitasking.

I included the untranslated strings in commit 118d170, but there's likely more untranslated strings.

audio and video download settings are saved if you enable the "save quality, format, and args" option in the settings.

Finally, I'll consider adding an option for that, but it's not on the height of importance.
