### ISSUE TITLE
No Win32?

### ISSUE THREAD

**Issue by Masutin** [murrty/youtube-dl-gui#4]
Won't run on XP 32?

**Comment by murrty** [comment]
I don't see why it shouldn't work on Windows XP, unless one of the other applications (youtube-dl or ffmpeg) don't run on it. Any other information other than it not running?

**Comment by Masutin** [comment]
Thanks for the reply! If I try to start youtube-dl-gui by hitting Enter in Total Commander, TC says Access Denied. If I try to start it while holding down Shift to see the process in a command prompt, a Windows message box says youtube-dl-gui is not a Win32 application and the console window says Access Denied.
XP SP3. FFmpeg is in %Path%; youtube-dl and -gui are in the same folder.

**Comment by murrty** [comment]
I can't say why it's saying access denied as I don't develop for it, but I can suggest that it might not have the right permissions to open the program, depending on where it is. I can't say for certain.

As far as Win32 error, try redownloading it. I think it's compiled for 32-bit systems, but I have not tested on 32-bit systems. I don't see why it wouldn't work. You can, however, recompile it for 32-bit systems if you

**Comment by murrty** [comment]
I looked more into it, and it seems like XP doesn't support .NET Framework 4.5, so, it won't be compatible with XP.

I am keeping this issue open, as I will probably release a compatible version for XP users, which won't be able to use updating since Github's API doesn't support TLS/1.0 anymore, and only 4.5 allows you to change the TLS used to 1.1/1.2. I will look into that to see if I will most definitely have to release a compatible version.

**Comment by murrty** [comment]
Hello, if you're still interested, I released youtube-dl-gui-compatible which uses .NET Framework 3.5, so it omits any updating included with the regular youtube-dl-gui.

As much as many others, it would be less of a headache if Github didn't revoke TLS/1.0 support, but here we are.
