### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by orezraey** [murrty/youtube-dl-gui#47]
Hello. I translated your app to portuguese, but I'm noob here and I don't know how to send it to you.
https://github.com/orezraey/youtube-dl-gui/blob/master/lang/Brazilian_portuguese.ini

**Comment by murrty** [comment]
You can open a pull request. I don't know how it's performed on the new github, since I haven't had to create one yet.

I'll add it and clean it up for you, but I honestly don't want to deal with translations through the issues tracker, but through pull requests so people can be added as a contributor on the repo.

**Comment by orezraey** [comment]
I didn't do it because I don't know xD just translated
