### ISSUE TITLE
Add more download/conversion formats

### ISSUE THREAD

**Issue by murrty1** [murrty/youtube-dl-gui#6]
I'm looking for any other extensions that I already did not get.

Video
1. Audio Video Interleave (*.avi)
2. Flash Video (*.flv)
3. MPEG-4 Part 14 (*.mp4)
4. Matroska (*.mkv)
5. QuickTime Movie (*.mov)
6. WebM (*.webm)
7. Windows Media Video (*.wmv)

Audio
1. Advanced Audio Codec (*.aac)
2. Free lossless Audio Codec (*.flac)
3. MPEG 4 Audio (*.m4a) (Can contain video as well)
4. MPEG-2 Audio Layer 3 (*.mp3)
5. Opus (*.opus)
6. Ogg Vorbis (*.ogg) (Can contain video as well)
7. Waveform Audio (*.wav)

**Comment by Dr-Flay** [comment]
Are you sure you mean MPEG-2 Layer 3 ?
That is not common and the usual MP3s are MPEG-1 Layer 3.
https://en.wikipedia.org/wiki/MPEG-1#Layer_III/MP3
MPEG-2 is used for MP3Pro files.

As M4A is a container format, you can put many things in there that you should not.
There may be files out there people have done this with, but it should not be encouraged because many players will not deal with it. That is what MP4 and M4V is for.
https://en.wikipedia.org/wiki/MPEG-4_Part_14#.MP4_versus_.M4A

OGG is also a container format, but Xiph have recommended since 2007 that people should not put video in there. That is what the extensions OGV and OGX are for.
Please only output OGG or OGA for audio.
https://en.wikipedia.org/wiki/Ogg

**Comment by murrty** [comment]
Thank you for this information.

I included m4a as an option in-case people require it, and I do prefer having backwards compatibility so I do plan on keeping it in.

As for ogg, I will set it as audio only and include the other three containers as additional options after a little more research into them.

**Comment by Dr-Flay** [comment]
I mostly use M4A so am not suggesting you get rid of it, only make sure that they just contain audio.

**Comment by drfrag666** [comment]
Speaking of m4a i cannot download playlists in that format. It works for individual files but only if i keep the quality at best i guess that's becouse it's actually 129 and not 128 (else it dowloads the webm). I select the audio download type and m4a format. But for playlists the app dowloads webm files and then converts them to m4a using ffmpeg. I want to avoid the conversion to prevent quality loss, by the way my mobile device doesn't support opus.

**Comment by Dr-Flay** [comment]
@drfrag666 This should be an issue/bug topic of its own.
It seems like the way YT-DL decides the highest quality is checking which is the biggest file size.
However with the more optimised WebM format, this is not a great way to decide on quality when at the same bitrate.

I have also noticed the same behaviour when downloading a playlist, where it will convert the file rather than fetch the one in that format.
I favour OPUS when the content is music related and the conversion happens that way also.

Regarding your mobile device and formats. The OS is not responsible for the formats your media player can play.
If you want OPUS support you need a player that supports it, just the same as a desktop OS.
For example you can install mobile VLC and play anything you could ever need.

**Comment by drfrag666** [comment]
The problem is much more serious, the apps lacks the basic functionality. Those options are for post processing, usually post processing is undesired since there's quality loss. You should be able to download the stream you choose. I would add a button to show what's there (-F option) and then a box to type the stream you want to download. Post processing should be optional (for instance you want to change the container for Opus audio from WebM to Ogg) but in general it could be handled by another app. The convert option is useless as usually you want to convert many files at once not selecting them one by one, you could remove that tab entirely to simplify things. I've uninstalled the app and i'll use the command line for basic stuff.
What usually happens with the app is that you download files in different formats (for the same playlist for instance), that depends on the popularity of the video it seems. And then many devices can't reproduce WebM audio.
