### ISSUE TITLE
Allow resume download on error

### ISSUE THREAD

**Issue by TheJayMann** [murrty/youtube-dl-gui#79]
Sometimes, whatever the reasons may be, a download may fail after having partially downloaded.  Youtube-dl, when ran again, can see that the file is partially downloaded, and is able to resume where it left off by simply running the command again with the same command line.  While doing a batch download of videos, if one or more of the downloads fail after having partially downloaded the video, attempting to download them again creates a new batch folder and restarts the download from the beginning.  It  would be nice if the download status form had a resume button on error which would restart the download process with the same command, which should resume where it left off.  As a workaround, I can copy the command displayed on the bottom of the download status form and manually invoke the youtube-dl command to resume the download.

* [x]  I would be willing to help implement and/or test this

**Comment by murrty** [comment]
I think the best course of action I want to do for this is add a retry button on the downloading form that appears when it's errored/aborted, but it might ruin the batch queue if someone downloads stuff while not at the computer.

Generally, the way that batch downloads work is that the time the batch download starts is temporary, so when you try to download the ones that failed, it'll download into a new batch download folder. I like it this way because if you do have stuff you want to have in a single folder and it errors, you can just move it back to the other folder.

I don't know how I want to handle this, I'll need some time to come up with something.

**Comment by TheJayMann** [comment]
My thoughts about this is, at least when doing a batch download (I haven't had a single download fail on me yet to know what happens).  When choosing to perform a batch download, the form appears which allows adding individual urls to build a list, and it has a start button.  Upon clicking the start button, the first url in the list has a blue down arrow to the side, and a new form appears showing the download status of that url.  Assuming it completes successfully, the download status form is closed, the url has a green checkbox next to it, the next url in the list has a blue down arrow, and a new download status form appears.  On failure, a sound is generated, the download status form remains open showing the error in the status area, the url in the list has a red cross, and the batch download is paused until the download status form is closed.  Once the download status form is closed, the next url in the list continues as described above.  Given this workflow, I would think that having a retry button appear (or become enabled) on failure in the download status form would work best, and, assuming it is the same form used when performing a single url download, it can work for both.

**Comment by TheJayMann** [comment]
Just to complete this issue, I tried 2.26pre3 version, and the retry button appears and works exactly as I expected it to.
