### ISSUE TITLE
yutube-dl-gui 2.26 Prerelase 3 - Italian language update

### ISSUE THREAD

**Issue by bovirus** [murrty/youtube-dl-gui#80]
@murrty 

I found a new beta release here

https://www.videohelp.com/software/youtube-dl-gui

but I didn't find any info and changes in this repository about language files.

What's the matter?

**Comment by murrty** [comment]
if you're feeling adventurous you can take a peek at [Language.cs](https://github.com/murrty/youtube-dl-gui/blob/master/Classes/Language.cs) which has all the internal names.

the reason the regular ini still isn't updated is because i'm still working on adjustments and the internal control names might change which might change in the language.cs class.

**Comment by bovirus** [comment]
@murrty 

No. 
It's just sound strange to find on VideoHelp web site new beta version of your program with new language files that I didn't  find here.
My expectation is to find here any beta/new language files.
